- hosts: jetsons
  tasks:
    - include: jetsons.yml
    - include: nfs.yml
    - include: leconte.yml
  vars:
    projectroot: /leconte
    projectgroup: leconte
    projectgid: 3004
    masternode: leconte-smokies.local
  tags: [jetsons]
